export const consumableData = {
	0: {
		id: 0,
		name: 'Pan de Incarnam',
		img: './res/image/consumable/0-0.png',
		description: 'Cura 30 de vida.',
		uses: [3, 3],
		price: 200,
		type: 'consumable',
		typeId: 9,
	},
	1: {
		id: 1,
		name: 'Pan dorado',
		img: './res/image/consumable/0-1.png',
		description: 'Cura 75 de vida. <br>Aumenta 5 la salud máxima.',
		uses: [1, 1],
		price: 500,
		type: 'consumable',
		typeId: 9,
	},
	2: {
		id: 2,
		name: 'Pan de avena',
		img: './res/image/consumable/0-2.png',
		description: 'Cura 150 de vida.',
		uses: [3, 3],
		price: 1000,
		type: 'consumable',
		typeId: 9,
	},
	3: {
		id: 3,
		name: 'Pan de molde',
		img: './res/image/consumable/0-3.png',
		description: 'Cura 300 de vida.',
		uses: [2, 2],
		price: 1600,
		type: 'consumable',
		typeId: 9,
	},
	4: {
		id: 4,
		name: 'Pergamino pequeño de fuerza',
		img: './res/image/consumable/1-0.png',
		description: 'Otorga 100 fuerza durante este combate.',
		uses: [1, 1],
		price: 800,
		type: 'consumable',
		typeId: 9,
	},
	5: {
		id: 5,
		name: 'Pergamino pequeño de inteligencia',
		img: './res/image/consumable/1-1.png',
		description: 'Otorga 100 inteligencia durante este combate.',
		uses: [1, 1],
		price: 800,
		type: 'consumable',
		typeId: 9,
	},
	6: {
		id: 6,
		name: 'Pergamino pequeño de agilidad',
		img: './res/image/consumable/1-2.png',
		description: 'Otorga 100 agilidad durante este combate.',
		uses: [1, 1],
		price: 800,
		type: 'consumable',
		typeId: 9,
	},
	7: {
		id: 7,
		name: 'Pergamino pequeño de suerte',
		img: './res/image/consumable/1-3.png',
		description: 'Otorga 100 suerte durante este combate.',
		uses: [1, 1],
		price: 800,
		type: 'consumable',
		typeId: 9,
	},
	8: {
		id: 8,
		name: 'Pan consistente',
		img: './res/image/consumable/0-4.png',
		description: 'Cura 300 de vida.<br> Restaura 100 de armadura.',
		uses: [4, 4],
		price: 2000,
		type: 'consumable',
		typeId: 9,
	},
	9: {
		id: 9,
		name: 'Pan de centeno',
		img: './res/image/consumable/0-5.png',
		description: 'Cura 800 de vida.',
		uses: [3, 3],
		price: 3000,
		type: 'consumable',
		typeId: 9,
	},
	10: {
		id: 10,
		name: 'Pócima matarratas',
		img: './res/image/consumable/2-0.png',
		description: 'Retira el veneno.',
		uses: [2, 2],
		price: 2400,
		type: 'consumable',
		typeId: 9,
	},
	11: {
		id: 11,
		name: 'Leleche',
		img: './res/image/consumable/2-1.png',
		description: 'Restaura toda la armadura.',
		uses: [1, 1],
		price: 2000,
		type: 'consumable',
		typeId: 9,
	},
	12: {
		id: 12,
		name: 'Pócima estrellada',
		img: './res/image/consumable/2-2.png',
		description: 'Restaura 6 PA.',
		uses: [2, 2],
		price: 4000,
		type: 'consumable',
		typeId: 9,
	},
	13: {
		id: 13,
		name: 'Frasco amarillo',
		img: './res/image/consumable/2-3.png',
		description: 'Convierte la resistencia a Aire del enemigo a 0%.',
		uses: [1, 1],
		price: 8000,
		type: 'consumable',
		typeId: 9,
	},
	14: {
		id: 14,
		name: 'Frasco rojo',
		img: './res/image/consumable/2-4.png',
		description: 'Convierte la resistencia a Fuego del enemigo a 0%.',
		uses: [1, 1],
		price: 8000,
		type: 'consumable',
		typeId: 9,
	},
	15: {
		id: 15,
		name: 'Frasco azul',
		img: './res/image/consumable/2-5.png',
		description: 'Convierte la resistencia a Agua del enemigo a 0%.',
		uses: [1, 1],
		price: 8000,
		type: 'consumable',
		typeId: 9,
	},
	16: {
		id: 16,
		name: 'Frasco verde',
		img: './res/image/consumable/2-6.png',
		description: 'Convierte la resistencia a Tierra del enemigo a 0%.',
		uses: [1, 1],
		price: 8000,
		type: 'consumable',
		typeId: 9,
	},
}