export const usableData = {
	0: {
		id: 0,
		name: 'Pergamino con hechizo',
		img: './res/image/usable/0-0.png',
		description: 'Escoge 1 entre 3 hechizos de clase. <br>No se podrá utilizar si ya tienes todos los hechizos.',
		price: 5000,
		type: 'usable',
		typeId: 10,
	},
	1: {
		id: 1,
		name: 'Cofre del tesoro',
		img: './res/image/usable/0-1.png',
		description: 'Escoge 1 entre 5 objetos exomágicos. <br>Su contenido cambia según la zona en la que se abra.',
		price: 5000,
		type: 'usable',
		typeId: 10,
	},
	2: {
		id: 2,
		name: 'Galleta enriquecida',
		img: './res/image/usable/0-2.png',
		description: 'Aumenta el poder de tu mascota.',
		price: 5000,
		type: 'usable',
		typeId: 10,
	},
	3: {
		id: 3,
		name: 'Pócima de olvido de hechizo',
		img: './res/image/usable/0-3.png',
		description: 'Olvida un hechizo. <br>No se podrá utilizar si no tienes ningún hechizo.',
		price: 5000,
		type: 'usable',
		typeId: 10,
	},
	4: {
		id: 4,
		name: 'Multigely',
		img: './res/image/usable/0-4.png',
		description: 'Gana +25 a Fuerza, Inteligencia, Agilidad y Suerte.',
		price: 5000,
		type: 'usable',
		typeId: 10,
	},
}